### ISSUE TITLE
Information on Release Process

### ISSUE THREAD

**Issue by ldts** [NXP/plug-and-trust#1]
Is there a release cadence for this project? 
how often do you plan on updating it from the SDK?

**Comment by ricardosalveti** [comment]
Latest release seems to be 03.00.06, is this repo going to be in sync with latest middleware?

**Comment by ldts** [comment]
notice there is an extension of this project [1] that is currently being used in OP-TEE [2] so the NXP SE050 can be controlled from a Trusted Execution Environment - something that is quite convenient for users wanting to establish a root of trust.

please could you confirm if the plug-and-trust project is going to be maintained? or perhaps it was only a drop?

[1] https://github.com/foundriesio/plug-and-trust
[2] https://github.com/OP-TEE/optee_os/tree/master/core/drivers/crypto/se050

**Comment by purnankNXP** [comment]
We plan to release this quarterly in line with official full Plug & Trust MW package (Released via NXP.com)
